import type { Metadata } from "next";
import { Cinzel, Almendra, Vollkorn } from 'next/font/google';
import "./globals.css";

const cinzel = Cinzel({
  subsets: ['latin'],
  weight: ['400', '700', '900'],
  variable: '--font-cinzel',
});

const almendra = Almendra({
  subsets: ['latin'],
  weight: ['400', '700'], // Almendra har bara vissa vikter
  variable: '--font-almendra',
});

const vollkorn = Vollkorn({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-vollkorn',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${cinzel.variable} ${almendra.variable} ${vollkorn.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
